# Section 1: Transpose of a Matrix and Symmetric Matrices

###Example: Transpose of a Matrix

In [1]:
import numpy as np

# Create a 3x3 matrix
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

In [2]:
# Find the transpose
transpose_A = matrix_A.T

print("Matrix A:\n", matrix_A)
print("\nTranspose of Matrix A:\n", transpose_A)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


###Symmetric Matrix

In [3]:
# Check if the matrix is symmetric
is_symmetric = (matrix_A == matrix_A.T).all()
print("\nIs Matrix A symmetric? ", is_symmetric)


Is Matrix A symmetric?  False


##Practice Problem 1

In [4]:
random_matrix = np.random.randint(1, 10, (4, 4))
transpose_random = random_matrix.T

In [5]:
# Check symmetry
is_symmetric_random = (random_matrix == transpose_random).all()
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric? ", is_symmetric_random)

Random Matrix:
 [[8 8 7 8]
 [4 1 5 7]
 [3 7 6 4]
 [5 8 6 1]]

Is the random matrix symmetric?  False


# Section 2: Trace of a Matrix

###Example

In [6]:
# Calculate the trace of matrix_A
trace_A = np.trace(matrix_A)
print("\nTrace of Matrix A:", trace_A)


Trace of Matrix A: 15


###Q3: What is the trace of the following matrix?

In [10]:
matrix_B = np.array([[10, 20, 30],
                   [5, 15, 25],
                   [2, 4, 6]])

In [11]:
# Calculate the trace of matrix_B
trace_B= np.trace(matrix_B)
print("\nTrace of Matrix A:", trace_B)


Trace of Matrix A: 31


##Practice Problem 2:

In [12]:
random_matrix_5x5 = np.random.rand(5, 5)
random_matrix_5x5

array([[0.72914003, 0.43651214, 0.83768994, 0.77026529, 0.92056283],
       [0.93123234, 0.44932007, 0.24563945, 0.036887  , 0.39500152],
       [0.29187337, 0.60363352, 0.72344067, 0.10930482, 0.24638829],
       [0.61299381, 0.06081419, 0.86074358, 0.84835347, 0.18940459],
       [0.37937313, 0.2855679 , 0.28560761, 0.60330291, 0.40389955]])

In [13]:
trace_random_matrix= np.trace(random_matrix_5x5)
print("\nTrace of Matrix A:", trace_random_matrix)


Trace of Matrix A: 3.1541537937294173


# Section 3: Determinant using the Cofactor Method

##Example: Determinant of a 3×3 Matrix

In [14]:
# Determinant using NumPy
det_A = np.linalg.det(matrix_A)
print("\nDeterminant of Matrix A:", det_A)


Determinant of Matrix A: 0.0


##Manual Cofactor Method

In [15]:
# Determinant of a 2x2 matrix using the cofactor method
matrix_C = np.array([[4, 6], [3, 8]])
det_C = (matrix_C[0, 0] * matrix_C[1, 1]) - (matrix_C[0, 1] * matrix_C[1, 0])
print("Determinant of Matrix C:", det_C)

Determinant of Matrix C: 14


##Practice Problem 3:

In [17]:
matrix_D = np.array([
    [1, 2, 3],
    [0, 4, 5],
    [1, 0, 6]
])

det_D = np.linalg.det(matrix_D)
print("Determinant of Matrix D:", det_D)

Determinant of Matrix D: 22.000000000000004


#Section 4: Practice Problems
##Practice Problem 4: Application in Computer Science


In [25]:
matrix_3x33 = np.random.randint(0, 256, size=(3, 33))
matrix_33x3 = np.random.randint(0, 256, size=(33, 3))

# Perform matrix multiplication
resultant_matrix = np.dot(matrix_3x33, matrix_33x3)

# Transpose and determinant
transpose = np.transpose(resultant_matrix)
determinant = np.linalg.det(resultant_matrix)

print("Transpose of the Resultant Matrix:", transpose)


print("Determinant of the Resultant Matrix:",determinant)

Transpose of the Resultant Matrix: [[528544 573183 468221]
 [471441 516625 397767]
 [539477 628096 498954]]
Determinant of the Resultant Matrix: 511861211404357.94


##Practice Problem 5: Symmetric Matrices in Machine Learning

In [24]:
symmetric_matrix = np.random.randint(0, 100, size=(3, 3))

is_symmetric = np.array_equal(symmetric_matrix, symmetric_matrix.T)

print("Symmetric Matrix:\n", symmetric_matrix)
print("\nIs the matrix symmetric?", is_symmetric)

Symmetric Matrix:
 [[98 81  8]
 [93 69 14]
 [20 61 79]]

Is the matrix symmetric? False
